<!doctype html>

<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=0.95">

  <title>Enduro</title>

  <script src="/assets/js/jquery-3.3.1.min.js"></script>

  <script type="text/javascript">
    window.onload = function() {
      $('.message a').click(function(){
        $('form').animate({height: "toggle", opacity: "toggle"}, "slow");
      });
    }
  </script>

  <link rel="stylesheet" href="/assets/css/style2.css"/>

</head>

<body>
  <div class="login-page">

    <div class="form">
      <p style="font-size: 2rem;"><b>Sistema de<br>Cronometragem<br>de Enduro</b></p>
      <p style="font-size: 1.25rem;"><u>Baja SAE Brasil Online</u></p>
      <br>
      <?php if(isset($error_message)): ?>
        <div class="error">
          <p><?= $error_message ?></p>
        </div>
      <?php endif; ?>
      <form class="register-form">
        <input type="text" placeholder="usuário"/>
        <input type="password" placeholder="senha"/>
        <input type="text" placeholder="e-mail"/>
        <button id="cadastrar">CRIAR CONTA</button>
        <p class="message">Já está cadastrado? <a href="#">Faça login</a></p>
      </form>
      <form class="login-form" action="/loginAction" method="post">
        <input id="login_name" name="login_name" type="text" placeholder="usuário"/>
        <input id="password" name="password" type="password" placeholder="senha"/>
        <button id="login">LOGIN</button>
        <p class="message">Não está cadastrado? <a href="#">Crie uma conta</a></p>
      </form>
    </div>
  </div>

<script type="text/javascript">
  document.getElementById('login_name').addEventListener("keydown", function(event) {
    if (event.keyCode === 13) {
      event.preventDefault();
      document.getElementById('password').focus();
    }
  });
</script>

</body>

</html>